/**
 * Default archetype definitions converted from the user's CSV spreadsheet.
 * Each archetype describes a play-style role with preferred sets, main stats,
 * and ordered substat priorities (S1 = highest value, S6 = lowest).
 *
 * null in a substat slot means "Any" — no preference, no scoring contribution.
 * null in fourPieceSets / twoPieceSets means any set is acceptable.
 * null in a mainStats array means any main stat is acceptable.
 *
 * setBonus  : score multiplier applied when item.set matches a preferred set.
 * mainBonus : score multiplier applied when item.main.type matches preferred main.
 */

export const DEFAULT_ARCHETYPES = [
    {
        id: 'opener',
        name: 'Opener',
        fourPieceSets: ['SpeedSet'],
        twoPieceSets: null,
        mainStats: {
            Necklace: [null],
            Ring: [null],
            Boots: ['Speed'],
        },
        substats: ['Speed', null, null, null, null, null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'debuffer-opener',
        name: 'Debuffer Opener',
        fourPieceSets: ['SpeedSet'],
        twoPieceSets: ['HitSet', 'ImmunitySet', 'HealthSet', 'TorrentSet', 'PursuitSet', 'DefenseSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', 'AttackPercent', null],
            Ring: ['EffectivenessPercent', 'HealthPercent', 'DefensePercent', null],
            Boots: ['Speed'],
        },
        substats: ['Speed', 'EffectivenessPercent', null, null, null, null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'cleanser-opener',
        name: 'Cleanser Opener',
        fourPieceSets: ['SpeedSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'ResistSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', null],
            Ring: ['EffectResistancePercent', 'HealthPercent', 'DefensePercent', null],
            Boots: ['Speed'],
        },
        substats: ['Speed', 'EffectResistancePercent', null, null, null, null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'crit-opener',
        name: 'Crit Opener',
        fourPieceSets: ['SpeedSet'],
        twoPieceSets: ['TorrentSet', 'PenetrationSet', 'PursuitSet', 'ImmunitySet', 'CriticalSet', 'HitSet'],
        mainStats: {
            Necklace: ['CriticalHitChancePercent', null],
            Ring: ['AttackPercent', 'EffectivenessPercent', 'Attack', null],
            Boots: ['Speed'],
        },
        substats: ['Speed', 'CriticalHitChancePercent', null, null, null, null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'fixed-dmg-opener',
        name: 'Fixed Dmg Opener',
        fourPieceSets: ['SpeedSet'],
        twoPieceSets: ['TorrentSet', 'PenetrationSet', 'PursuitSet', 'ImmunitySet', 'CriticalSet', 'HitSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'Attack', null],
            Ring: ['AttackPercent', 'EffectivenessPercent', 'Attack', null],
            Boots: ['Speed'],
        },
        substats: ['Speed', 'AttackPercent', 'HealthPercent', 'DefensePercent', null, null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'dps',
        name: 'DPS',
        fourPieceSets: ['SpeedSet', 'AttackSet', 'CounterSet', 'DestructionSet', 'RageSet', 'RevengeSet', 'RiposteSet', 'WarfareSet', 'LifestealSet'],
        twoPieceSets: ['CriticalSet', 'ImmunitySet', 'PenetrationSet', 'TorrentSet', 'PursuitSet', 'UnitySet'],
        mainStats: {
            Necklace: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'AttackPercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Attack', null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'dps-always-crit',
        name: 'Dps Always Crit',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'AttackSet', 'RageSet', 'RevengeSet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet'],
        twoPieceSets: ['ImmunitySet', 'TorrentSet', 'PursuitSet', 'PenetrationSet'],
        mainStats: {
            Necklace: ['CriticalHitDamagePercent', 'AttackPercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'CriticalHitDamagePercent', 'Attack', 'HealthPercent', null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'tank',
        name: 'Tank',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'SpeedSet', 'ProtectionSet', 'ReversalSet', 'WarfareSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Ring: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Boots: ['Speed', 'HealthPercent', 'DefensePercent'],
        },
        substats: ['HealthPercent', 'DefensePercent', 'Speed', 'Defense', 'Health', null],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'er-tank',
        name: 'ER Tank',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'SpeedSet', 'ProtectionSet', 'ReversalSet', 'WarfareSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'ResistSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Ring: ['EffectResistancePercent', 'HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Boots: ['Speed', 'HealthPercent', 'DefensePercent'],
        },
        substats: ['HealthPercent', 'DefensePercent', 'Speed', 'EffectResistancePercent', 'Defense', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'eff-tank',
        name: 'EFF Tank',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'RageSet', 'SpeedSet', 'ProtectionSet', 'ReversalSet', 'WarfareSet'],
        twoPieceSets: ['HitSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Ring: ['EffectivenessPercent', 'HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Boots: ['Speed', 'HealthPercent', 'DefensePercent'],
        },
        substats: ['HealthPercent', 'EffectivenessPercent', 'Speed', 'DefensePercent', 'Defense', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'eff-er-tank',
        name: 'Eff/ER Tank',
        fourPieceSets: ['CounterSet', 'RageSet', 'RevengeSet', 'SpeedSet', 'ProtectionSet', 'ReversalSet', 'WarfareSet'],
        twoPieceSets: ['HitSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'ResistSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Ring: ['EffectivenessPercent', 'EffectResistancePercent', 'HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Boots: ['Speed', 'HealthPercent', 'DefensePercent'],
        },
        substats: ['HealthPercent', 'Speed', 'EffectivenessPercent', 'EffectResistancePercent', 'DefensePercent', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-er-cant-crit',
        name: 'Atk + ER Cant Crit',
        fourPieceSets: ['AttackSet', 'CounterSet', 'RevengeSet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet'],
        twoPieceSets: ['PursuitSet', 'TorrentSet', 'ResistSet', 'PenetrationSet', 'HealthSet', 'ImmunitySet', 'DefenseSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'Attack'],
            Ring: ['EffectResistancePercent', 'AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'EffectResistancePercent', 'Attack', 'HealthPercent', 'DefensePercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-eff-cant-crit',
        name: 'Atk + EFF Cant Crit',
        fourPieceSets: ['AttackSet', 'CounterSet', 'RageSet', 'RevengeSet', 'SpeedSet', 'RiposteSet'],
        twoPieceSets: ['HitSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'TorrentSet', 'PursuitSet', 'PenetrationSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'Attack'],
            Ring: ['EffectivenessPercent', 'AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'EffectivenessPercent', 'Attack', 'HealthPercent', 'DefensePercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-eff-can-crit',
        name: 'Atk + Eff Can Crit',
        fourPieceSets: ['AttackSet', 'CounterSet', 'DestructionSet', 'RageSet', 'InjurySet', 'SpeedSet'],
        twoPieceSets: ['HitSet', 'CriticalSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Attack'],
            Ring: ['EffectivenessPercent', 'AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'EffectivenessPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Attack'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-eff-can-crit',
        name: 'Hp + Eff Can Crit',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RageSet', 'InjurySet', 'SpeedSet'],
        twoPieceSets: ['HitSet', 'CriticalSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'CriticalHitChancePercent', 'CriticalHitDamagePercent', 'Health'],
            Ring: ['EffectivenessPercent', 'HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['HealthPercent', 'Speed', 'EffectivenessPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-eff-always-crit',
        name: 'Hp + Eff Always Crit',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RageSet', 'InjurySet', 'SpeedSet'],
        twoPieceSets: ['HitSet', 'CriticalSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'CriticalHitDamagePercent', 'Health'],
            Ring: ['EffectivenessPercent', 'HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['HealthPercent', 'Speed', 'EffectivenessPercent', 'CriticalHitDamagePercent', 'Health', 'DefensePercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'bruiser',
        name: 'Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'InjurySet', 'SpeedSet', 'LifestealSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['CriticalHitDamagePercent', 'CriticalHitChancePercent'],
            Ring: ['HealthPercent', 'DefensePercent', 'Defense', 'Health'],
            Boots: ['Speed'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'HealthPercent', 'DefensePercent', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-bruiser',
        name: 'Atk Bruiser',
        fourPieceSets: ['AttackSet', 'CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['CriticalSet', 'DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'AttackPercent', 'HealthPercent', 'DefensePercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-bruiser-always-crit',
        name: 'Atk Bruiser Always Crit',
        fourPieceSets: ['AttackSet', 'CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'CriticalHitDamagePercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'Speed', 'AttackPercent', 'HealthPercent', 'DefensePercent', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-bruiser',
        name: 'Hp Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Health'],
            Ring: ['HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'HealthPercent', 'DefensePercent', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-bruiser-always-crit',
        name: 'Hp Bruiser Always Crit',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'CriticalHitDamagePercent', 'Health'],
            Ring: ['HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'Speed', 'HealthPercent', 'DefensePercent', 'Health', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'def-bruiser',
        name: 'Def Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet', 'CriticalSet'],
        mainStats: {
            Necklace: ['DefensePercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Defense'],
            Ring: ['DefensePercent', 'Defense'],
            Boots: ['Speed', 'DefensePercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'DefensePercent', 'HealthPercent', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'def-bruiser-always-crit',
        name: 'Def Bruiser Always Crit',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['DefensePercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Defense'],
            Ring: ['DefensePercent', 'Defense'],
            Boots: ['Speed', 'DefensePercent'],
        },
        substats: ['CriticalHitDamagePercent', 'Speed', 'DefensePercent', 'HealthPercent', 'Defense', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-bruiser-cant-crit',
        name: 'Atk Bruiser Cant Crit',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet', 'AttackSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'HealthPercent', 'DefensePercent', 'Attack', 'Defense'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-bruiser-cant-crit',
        name: 'Hp Bruiser Cant Crit',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'Health'],
            Ring: ['HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['HealthPercent', 'Speed', 'DefensePercent', 'Defense', 'Health', 'AttackPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'def-bruiser-cant-crit',
        name: 'Def Bruiser Cant Crit',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet'],
        mainStats: {
            Necklace: ['DefensePercent', 'Defense'],
            Ring: ['DefensePercent', 'Defense'],
            Boots: ['Speed', 'DefensePercent'],
        },
        substats: ['DefensePercent', 'Speed', 'HealthPercent', 'Defense', 'Health', 'AttackPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'er-atk-bruiser',
        name: 'ER Atk Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'AttackSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet', 'CriticalSet', 'ResistSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Attack'],
            Ring: ['AttackPercent', 'EffectResistancePercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'AttackPercent', 'EffectResistancePercent', 'HealthPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'er-hp-bruiser',
        name: 'ER Hp Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'PursuitSet', 'CriticalSet', 'ResistSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Health'],
            Ring: ['HealthPercent', 'EffectResistancePercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'HealthPercent', 'EffectResistancePercent', 'DefensePercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'er-def-bruiser',
        name: 'ER Def Bruiser',
        fourPieceSets: ['CounterSet', 'DestructionSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PenetrationSet', 'TorrentSet', 'PursuitSet', 'CriticalSet', 'ResistSet'],
        mainStats: {
            Necklace: ['DefensePercent', 'CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Defense'],
            Ring: ['DefensePercent', 'EffectResistancePercent', 'Defense'],
            Boots: ['Speed', 'DefensePercent'],
        },
        substats: ['CriticalHitDamagePercent', 'CriticalHitChancePercent', 'Speed', 'DefensePercent', 'EffectResistancePercent', 'HealthPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'atk-fixed-dmg-bruiser',
        name: 'Atk Fixed Dmg Bruiser',
        fourPieceSets: ['AttackSet', 'CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet', 'PenetrationSet', 'TorrentSet'],
        mainStats: {
            Necklace: ['AttackPercent', 'Attack'],
            Ring: ['AttackPercent', 'Attack'],
            Boots: ['Speed', 'AttackPercent'],
        },
        substats: ['AttackPercent', 'Speed', 'HealthPercent', 'DefensePercent', 'Defense', 'Health'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'hp-fixed-dmg-bruiser',
        name: 'Hp Fixed Dmg Bruiser',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ProtectionSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet', 'PenetrationSet'],
        mainStats: {
            Necklace: ['HealthPercent', 'Health'],
            Ring: ['HealthPercent', 'Health'],
            Boots: ['Speed', 'HealthPercent'],
        },
        substats: ['HealthPercent', 'Speed', 'DefensePercent', 'Health', 'Defense', 'AttackPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
    {
        id: 'def-fixed-dmg-bruiser',
        name: 'Def Fixed Dmg Bruiser',
        fourPieceSets: ['CounterSet', 'RevengeSet', 'InjurySet', 'SpeedSet', 'LifestealSet', 'RiposteSet', 'WarfareSet', 'ReversalSet'],
        twoPieceSets: ['DefenseSet', 'ImmunitySet', 'HealthSet', 'PursuitSet', 'PenetrationSet', 'TorrentSet'],
        mainStats: {
            Necklace: ['DefensePercent', 'Defense'],
            Ring: ['DefensePercent', 'Defense'],
            Boots: ['Speed', 'DefensePercent'],
        },
        substats: ['DefensePercent', 'Speed', 'HealthPercent', 'Defense', 'Health', 'AttackPercent'],
        setBonus: 1.25,
        mainBonus: 1.5,
    },
];

// ---------------------------------------------------------------------------
// Assign default groups to each built-in archetype.
// ---------------------------------------------------------------------------
{
    const GROUPS = {
        'opener':             'Opener',
        'debuffer-opener':    'Opener',
        'cleanser-opener':    'Opener',
        'crit-opener':        'Opener',
        'fixed-dmg-opener':   'Opener',
        'dps':                'DPS',
        'dps-always-crit':    'DPS',
        'tank':               'Tank',
        'er-tank':            'Tank',
        'eff-tank':           'Tank',
        'eff-er-tank':        'Tank',
        'atk-er-cant-crit':   'Attacker',
        'atk-eff-cant-crit':  'Attacker',
        'atk-eff-can-crit':   'Attacker',
        'hp-eff-can-crit':    'HP DPS',
        'hp-eff-always-crit': 'HP DPS',
    };
    DEFAULT_ARCHETYPES.forEach((a) => {
        a.group = GROUPS[a.id] || 'Bruiser';
    });
}

export default DEFAULT_ARCHETYPES;
